### ISSUE TITLE
Error when authenticating

### ISSUE THREAD

**Issue by dphaener** [nixme/pandora_client#3]
I'm getting the following error when trying to authenticate a user:

/home/darin/.rvm/gems/ruby-2.0.0-p247/gems/crypt-1.1.4/crypt/blowfish.rb:47:in `|': String can't be coerced into Fixnum (TypeError)
    from /home/darin/.rvm/gems/ruby-2.0.0-p247/gems/crypt-1.1.4/crypt/blowfish.rb:47:in`block (2 levels) in setup_blowfish'
    from /home/darin/.rvm/gems/ruby-2.0.0-p247/gems/crypt-1.1.4/crypt/blowfish.rb:46:in `times'
    from /home/darin/.rvm/gems/ruby-2.0.0-p247/gems/crypt-1.1.4/crypt/blowfish.rb:46:in`block in setup_blowfish'
    from /home/darin/.rvm/gems/ruby-2.0.0-p247/gems/crypt-1.1.4/crypt/blowfish.rb:44:in `upto'
    from /home/darin/.rvm/gems/ruby-2.0.0-p247/gems/crypt-1.1.4/crypt/blowfish.rb:44:in`setup_blowfish'
    from /home/darin/.rvm/gems/ruby-2.0.0-p247/gems/crypt-1.1.4/crypt/blowfish.rb:27:in `initialize'
    from /home/darin/code/pandora_client/lib/pandora/util/cryptor.rb:15:in`new'
    from /home/darin/code/pandora_client/lib/pandora/util/cryptor.rb:15:in `initialize'
    from /home/darin/code/pandora_client/lib/pandora/partner.rb:39:in`new'
    from /home/darin/code/pandora_client/lib/pandora/partner.rb:39:in `cryptor'
    from /home/darin/code/pandora_client/lib/pandora/partner.rb:54:in`authenticate'
    from /home/darin/code/pandora_client/lib/pandora/partner.rb:14:in `initialize'
    from /home/darin/code/pandora_client/lib/pandora_client.rb:9:in`new'
    from /home/darin/code/pandora_client/lib/pandora_client.rb:9:in `<main>'

Any ideas?

**Comment by nixme** [comment]
I haven't touched this lib in a while, sorry. @archit, any ideas.

**Comment by nixme** [comment]
Actually, that's odd. This gem depends on crypt19-rb for Ruby 1.9+ support. The old crypt gem won't work.

**Comment by nixme** [comment]
If you have this repo cloned locally, run `bundle --path vendor/bundle` first and then run `bundle exec pry` or `bundle exec ruby` so it picks up the right dependencies.

**Comment by archit** [comment]
This may be useful, https://www.ruby-forum.com/topic/203985

**Comment by dphaener** [comment]
Thanks guys, that cleared it up. I'm good to go now. Thanks for the gem!

Darin
